version: "2"

services: 
  jenkins-backup:
    image: openjdk:8-jdk-alpine
    volumes: 
    - ${JENKINS_HOME}:/jenkins_home
    - ${JENKINS_BACKUP_HOME}:/backup
    command: ["tar", "--exclude=workspace", "-cvf", "/backup/jenkins-home.tar", "/jenkins_home"]