version: "2"

services:
  
  jenkins:
    image: ${REGISTRY_URL}/jenkins:0.1-svntunnel
    extends:
      file: common-service.yml
      service: logging
    ports:
    - ${JENKINS_REMOTE_API_PORT}:50000
    volumes: 
    - ${JENKINS_HOME}:/var/jenkins_home
    networks: 
      default:
      hub_net:
        aliases:
        - builder

networks: 
  hub_net:
    external: true