version: "2"

services:
  jenkins:
    build: jenkins
    ports:
    - ${JENKINS_REMOTE_API_PORT}:50000
    - ${JENKINS_HTTP_PORT}:8080
    volumes: 
    - ${JENKINS_HOME}:/var/jenkins_home
    environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_S3_PROXY_SSH_KEY